### ISSUE TITLE
With firmware V1.0.2.75.2SF IPV6 DNS server appears to be set incorrectly

### ISSUE THREAD

**Issue by z4ce** [SVoxel/R7800#8]
The DNS server that DHCP hands out gets set to fe80::12da:43ff:fe14:a94d which isn't routable from the wireless lan. I believe it should be handing out 2600:1700:a7d0:9a2f:12da:43ff:fe14:a94d

**Comment by z4ce** [comment]
I'm also thinking its possible that at some point the first IP address was routable but a change in firewall rules is preventing that traffic now

**Comment by grancier** [comment]
@SVoxel I'm using your firmware for Nighthawk X4S (7800), and I cannot enter "192.221.159.0" as primary dns address, even though that is a valid address. (for example if you 'ping' above IP it works)

This is because the function checkipaddr in funcs.js doesn't do proper ipv4 validation, and I get an error when entering the IP. 

Can this be fixed in a future release? thanks.

**Comment by SVoxel** [comment]
Well, sorry for delay. I am locked far away from my R7800 in router mode (COVID-19).

First, I cannot test IPv6 because of my ISP does not support IPv6. Sorry.

Second, 192.221.159.0. As I said, I am far away from my R7800. I am not sure I can access it soon enough. Try to set your DNS through nvram (quick workaround) 

nvram set wan_ether_dns1=192.221.159.0
nvram commit

Voxel.
